# Generated by Django 2.2.6 on 2019-10-09 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField()),
                ('name', models.CharField(max_length=400)),
                ('mem', models.FloatField()),
                ('cpu', models.FloatField()),
                ('disk', models.FloatField()),
                ('gpu', models.FloatField()),
                ('network', models.FloatField()),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
