# Generated by Django 2.2.6 on 2019-10-10 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proc',
            name='cpu',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='proc',
            name='disk',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='proc',
            name='gpu',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='proc',
            name='mem',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='proc',
            name='network',
            field=models.FloatField(null=True),
        ),
    ]
